
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000 

development:
  <<: *default
  database: myapp_development
  username: tutorial
  password: tutorial

# test:
#   <<: *default


# production:
#   <<: *default

